[package]
name = "crawl"
version = "0.1.0"
authors = ["yml <yuemenglong@126.com>"]

[dependencies]
html5ever = "*"
hyper = "0.9.13"
regex = "*"
rustc-serialize = "0.3.21"
chrono = { version = "0.2", features = ["serde", "rustc-serialize"] }

[dependencies.orm]
path = "../orm"
